# Pleb.One Configuration
# Default configuration for all environments

[environment]
name = "development"
debug = true

[server]
port = 8000
read_timeout = "30s"
write_timeout = "30s"
idle_timeout = "120s"

[relay]
port = 8080
health_port = 8081
max_connections = 10000
max_subscriptions_per_connection = 20
event_batch_size = 100
event_batch_timeout = "100ms"

[database]
url = "postgres://pleb_one:development@localhost:5432/pleb_one"
max_connections = 20
min_connections = 5
connection_timeout = "30s"
idle_timeout = "10m"
max_lifetime = "1h"

[cache]
url = "redis://localhost:6379"
password = ""
db = 0
max_retries = 3
min_retry_backoff = "100ms"
max_retry_backoff = "3s"
pool_size = 10

[auth]
jwt_secret = "development-secret-change-in-production"
jwt_expiry = "24h"
refresh_token_expiry = "7d"
bcrypt_cost = 12
session_timeout = "24h"

[metrics]
enabled = true
port = 9090
path = "/metrics"
namespace = "pleb_one"

[logging]
level = "info"
format = "json"
output = "stdout"

[cors]
allowed_origins = ["http://localhost:3000", "http://localhost:8000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Request-ID"]
expose_headers = ["X-Request-ID"]
allow_credentials = true
max_age = "12h"

[rate_limiting]
enabled = true
requests_per_minute = 100
burst_size = 10
cleanup_interval = "1m"

# Subscription pricing (in satoshis)
[pricing]
monthly_price = 3500
annual_discount = 0.15  # 15% discount for annual subscriptions
grace_period = "3d"     # Grace period after payment failure

# Lightning Network configuration
[lightning]
node_url = "http://localhost:8080"
network = "bitcoin"
invoice_expiry = "1h"
webhook_url = "http://localhost:8001/webhooks/lightning"

# Email configuration
[email]
smtp_host = "localhost"
smtp_port = 1025
smtp_user = ""
smtp_password = ""
from_address = "noreply@pleb.one"
from_name = "Pleb.One"

# Feature flags
[features]
registration_enabled = true
subscription_required = true
community_governance = true
educational_content = true
api_documentation = true

# Security settings
[security]
password_min_length = 8
require_email_verification = true
max_login_attempts = 5
lockout_duration = "15m"
csrf_protection = true
content_security_policy = true

# Performance settings
[performance]
max_request_size = "10MB"
request_timeout = "30s"
keepalive_timeout = "60s"
max_header_size = "8KB"

# Monitoring and observability
[monitoring]
jaeger_endpoint = "http://localhost:14268/api/traces"
prometheus_enabled = true
health_check_interval = "30s"
metrics_collection_interval = "10s"

# Development specific settings
[development]
hot_reload = true
debug_sql = false
seed_data = true
mock_lightning = true
bypass_email_verification = true
