[package]
name = "pleb-one-relay-engine"
version = "0.1.0"
edition = "2021"
description = "High-performance Nostr relay engine for Pleb.One"

[dependencies]
# Internal dependencies
pleb-one-nostr-types = { path = "../nostr-types" }
pleb-one-storage = { path = "../storage-layer" }
pleb-one-config = { path = "../config-manager" }

# External dependencies
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
redis = { workspace = true }
hex = { workspace = true }
secp256k1 = { workspace = true }
sha2 = { workspace = true }
futures-util = { workspace = true }
dashmap = { workspace = true }
tower = { workspace = true }
axum = { workspace = true }
prometheus = { workspace = true }
