global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'relay-engine'
    static_configs:
      - targets: ['relay-engine:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
